### ISSUE TITLE
Repository.create_fork fails on Python 2.x if user is in a Github org

### ISSUE THREAD

**Issue by absurdfarce** [datastax/adelphi#70]
Documenting this here mainly so that there's a record of it.  Fix will likely be implemented as part of the ongoing work for https://github.com/datastax/adelphi/issues/67.

Observed while attempting to run "adelphi contribute" using Python 2.x after switching code to use the repo at datastax/adelphi-schemas (which is in the "datastax" organization):

```python
Traceback (most recent call last):
  File "/work/git/adelphi/python/setup/bin/adelphi", line 202, in <module>
    export(obj={}, auto_envvar_prefix="ADELPHI")
  File "/work/git/adelphi/python/setup/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/work/git/adelphi/python/setup/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/work/git/adelphi/python/setup/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/work/git/adelphi/python/setup/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/work/git/adelphi/python/setup/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/work/git/adelphi/python/setup/lib/python2.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/work/git/adelphi/python/setup/bin/adelphi", line 196, in contribute
    fork_repo = origin_repo.create_fork()
  File "/work/git/adelphi/python/setup/lib/python2.7/site-packages/github/Repository.py", line 2088, in create_fork
    "POST", self.url + "/forks", input=post_parameters,
  File "/work/git/adelphi/python/setup/lib/python2.7/site-packages/github/Requester.py", line 322, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/work/git/adelphi/python/setup/lib/python2.7/site-packages/github/Requester.py", line 413, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/work/git/adelphi/python/setup/lib/python2.7/site-packages/github/Requester.py", line 470, in __requestEncode
    requestHeaders["Content-Type"], encoded_input = encode(input)
  File "/work/git/adelphi/python/setup/lib/python2.7/site-packages/github/Requester.py", line 411, in encode
    return "application/json", json.dumps(input)
  File "/usr/lib64/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: NotSet is not JSON serializable
```

Underlying problem here is the Repository.create_fork function.  That function in v1.45 of PyGithub is as follows:

```python
    def create_fork(self, organization=github.GithubObject.NotSet):
        """                                                                                                                                                                       
        :calls: `POST /repos/:owner/:repo/forks <http://developer.github.com/v3/repos/forks>`_                                                                                    
        :param organization: string or "none" or "*"                                                                                                                              
        :rtype: :class:`github.Repository.Repository`                                                                                                                             
        """
        assert organization is github.GithubObject.NotSet or isinstance(
            organization, (str, six.text_type)
        ), organization
        post_parameters = {}
        if organization is not None:
            post_parameters["organization"] = organization
        headers, data = self._requester.requestJsonAndCheck(
            "POST", self.url + "/forks", input=post_parameters,
        )
        return Repository(self._requester, headers, data, completed=True)
```

Note the disconnect: the assertion is centered around a check for NotSet (which is the default value) but the val is added to post_parameters if the organization is not None.  This results in the non-serializable NotSet being added to the outgoing HTTP request... which ultimately results in the TypeError shown above.

This bug was identified and fixed in https://github.com/PyGithub/PyGithub/pull/1383.  The problem is that (a) that fix wasn't rolled out until PyGithub 1.46 (see https://github.com/PyGithub/PyGithub/releases/tag/v1.46) and (b) the last version of PyGithub that supports Python 2.x is 1.45 (see https://github.com/PyGithub/PyGithub/releases/tag/v1.45).

Upshot is that if you use Python 2.x you'll get a version of PyGithub that includes this bug.  If the user your Github token comes from is in an organization this becomes very problematic since you have to specify whether you want the fork created in the org or in your personal space.  For extra fun no value of the organization param in the function below will accomplish that goal: if you pass None you'll fail the assertion but if you pass NotSet you'll hit the JSON serialization issue.

**Comment by absurdfarce** [comment]
This will be addressed in the PR for https://github.com/datastax/adelphi/issues/67
