### ISSUE TITLE
export-gemini fails using Python 3.9.0

### ISSUE THREAD

**Issue by jdonenine** [datastax/adelphi#76]
When trying to run an export of gemini formated schema, the run fails when using python 3.

You can see the problem here:

```
jeffdinoto@jdinoto-rmbp16 adelphi % pyenv local 3.9.0
jeffdinoto@jdinoto-rmbp16 adelphi % pip install .
Processing /Users/jeffdinoto/github/public/datastax/adelphi/python/adelphi
Collecting cassandra-driver~=3.24.0
  Using cached cassandra-driver-3.24.0.tar.gz (283 kB)
Requirement already satisfied: click~=7.1.0 in /Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from adelphi==0.1.0) (7.1.2)
Requirement already satisfied: PyGithub~=1.45 in /Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from adelphi==0.1.0) (1.53)
Requirement already satisfied: six>=1.9 in /Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from cassandra-driver~=3.24.0->adelphi==0.1.0) (1.15.0)
Requirement already satisfied: geomet<0.3,>=0.1 in /Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from cassandra-driver~=3.24.0->adelphi==0.1.0) (0.2.1.post1)
Requirement already satisfied: pyjwt in /Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from PyGithub~=1.45->adelphi==0.1.0) (1.7.1)
Requirement already satisfied: requests>=2.14.0 in /Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from PyGithub~=1.45->adelphi==0.1.0) (2.25.0)
Requirement already satisfied: deprecated in /Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from PyGithub~=1.45->adelphi==0.1.0) (1.2.10)
Requirement already satisfied: idna<3,>=2.5 in /Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from requests>=2.14.0->PyGithub~=1.45->adelphi==0.1.0) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from requests>=2.14.0->PyGithub~=1.45->adelphi==0.1.0) (1.26.2)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from requests>=2.14.0->PyGithub~=1.45->adelphi==0.1.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from requests>=2.14.0->PyGithub~=1.45->adelphi==0.1.0) (2020.11.8)
Requirement already satisfied: wrapt<2,>=1.10 in /Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages (from deprecated->PyGithub~=1.45->adelphi==0.1.0) (1.12.1)
Using legacy 'setup.py install' for adelphi, since package 'wheel' is not installed.
Using legacy 'setup.py install' for cassandra-driver, since package 'wheel' is not installed.
Installing collected packages: cassandra-driver, adelphi
    Running setup.py install for cassandra-driver ... /
done
    Running setup.py install for adelphi ... done
Successfully installed adelphi-0.1.0 cassandra-driver-3.24.0
WARNING: You are using pip version 20.2.4; however, version 20.3.3 is available.
You should consider upgrading via the '/Users/jeffdinoto/.pyenv/versions/3.9.0/bin/python -m pip install --upgrade pip' command.
jeffdinoto@jdinoto-rmbp16 adelphi % python -V                                                                                    
Python 3.9.0
jeffdinoto@jdinoto-rmbp16 adelphi % adelphi --hosts=localhost --username=cassandra --password=cassandra --anonymize export-gemini
WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 127.0.0.1:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 4 for 127.0.0.1:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
INFO:cassandra.policies:Using datacenter 'datacenter1' for DCAwareRoundRobinPolicy (via host '127.0.0.1:9042'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
INFO:cassandra.cluster:Cassandra host ::1:9042 removed
INFO:adelphi:Excluding system keyspaces system_auth,system_schema,system_distributed,system,system_traces
INFO:adelphi:Processing the following keyspaces: datastax_iot_demo
Traceback (most recent call last):
  File "/Users/jeffdinoto/.pyenv/versions/3.9.0/bin/adelphi", line 269, in <module>
    export(obj={}, auto_envvar_prefix="ADELPHI")
  File "/Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jeffdinoto/.pyenv/versions/3.9.0/bin/adelphi", line 231, in export_gemini
    export_keyspaces(ctx.obj, export_gemini_schema, keyspace_map, metadata)
  File "/Users/jeffdinoto/.pyenv/versions/3.9.0/bin/adelphi", line 200, in export_keyspaces
    print(export_fn(keyspace_map.keys(), metadata, options))
  File "/Users/jeffdinoto/.pyenv/versions/3.9.0/lib/python3.9/site-packages/adelphi/gemini.py", line 30, in export_gemini_schema
    keyspace = keyspace_objs[0]
TypeError: 'dict_keys' object is not subscriptable
```

The problem does no occur when running with python 2.7.18

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/AD-59) by [Unito](https://www.unito.io)
┆Issue Number: AD-59

**Comment by jdonenine** [comment]
A quick test on master looks like this is only a problem on the branch being used for the #71 fixes
